### ISSUE TITLE
Question: How do I perform a find by slug when I do not have the suglified string? 

### ISSUE THREAD

**Issue by angelxmoreno** [jarrodconnolly/sequelize-slugify#1]
Scenario:
I have a model called `Author` like so:

    'use strict';
    var SequalizeSlugify = require('sequelize-slugify');
    module.exports = function (sequelize, DataTypes) {
        var Author = sequelize.define('Author', {
            slug: {
                type: DataTypes.STRING,
                unique: true
            },
            name: {
                type: DataTypes.STRING,
                allowNull: false,
                unique: true
            }
        }, {
            tableName: 'authors',
            paranoid: true,
            underscored: true,
            classMethods: {
                associate: function (models) {
                    Author.belongsToMany(models.Book, {as: 'BookAuthor', through: 'books_authors'});
                }
            }
        });
        SequalizeSlugify.slugifyModel(Author, {
            source: ['name']
        });
        return Author;
    };

Now I would like to do a find given an unslugified author name. 

    Author.FindOne({
        where: {
            slug: SequalizeSlugify.somethingmagical("John Doe")
    });

**Comment by jarrodconnolly** [comment]
Trying to fully understand your use case.

If you have the name already can you not search by that field?

Slugs are most often used to make a given field or set of fields "url safe". They would be put into a url then used again server side to look up the user by its slug when it is passed back to you.

For example, if you had some edit user profile type screen it may look like this:

`https://www.site.com/user/profile/john-doe`

In this case `john-doe` is the slugified version of the name field that you would then use to look up the user again on a post.

They are also helpful to keep urls SEO friendly or semantic instead of using an id or guid on the url. Anything not allowed in a url will neatly be replaced such as spaces and most symbol characters.

I am not sure if a lookup of the type you are trying would be possible since there can also be multiple slugified version of the same string. I realize if your case the name field is unique but often there are and you end up with slugs like this.

`john-doe`
`john-doe-1`
`john-doe-2`

In those cases just passing the original name is not enough data to recreate the slug that it had originally created.

I hope this helps you understand, let me know if you have any further questions.

Some further information on semantic urls.
https://en.wikipedia.org/wiki/Semantic_URL

**Comment by angelxmoreno** [comment]
The bigger picture is that data is coming from an API. I worked around it. Thank you.
